# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(null=True, to='event_manager.Member'),
        ),
    ]
