# Generated by Django 2.0 on 2017-12-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='netid',
            field=models.IntegerField(default='null'),
        ),
        migrations.AlterField(
            model_name='member',
            name='points',
            field=models.IntegerField(),
        ),
    ]
