# Generated by Django 2.0 on 2017-12-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_auto_20171219_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='netid',
            field=models.IntegerField(default=0),
        ),
    ]
