# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0003_auto_20171103_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(blank=True, to='event_manager.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_manager.Team'),
        ),
    ]
